from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name= "books.index"),
    path('list_books/', views.list_books, name= "books.list_books"),
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
    path('singlebook/<int:Id>',views.singleBook,name='books.showsinglebook'),
    path('aboutus/', views.aboutus, name="books.aboutus"),
    path('html5/links/', views.links, name = "books.html5.links"),
    path('html5/text/Formatting/', views.formatting, name= 'books.html5.formating'),
    path('html5/Listing/', views.listing, name= 'books.html5.Listing'),
    path('html5/tables/',views.tables, name= 'books.html5.tables'),
    path('search/',views.search, name="books.search"),
    path('simple/query/',views.simple_query, name="books.simple_query"),
    path('complex/query/',views.lookup_query,name="book.lookup_query"),
    path('lab8/task1/', views.task1, name="books.lab8.task1"),
    path('lab8/task2/',views.task2,name="books.lab8.task2"),
    path('lab8/task3/',views.task3,name="books.lab8.task3"),
    path('lab8/task4/',views.task4,name="books.lab8.task4"),
    path('lab8/task5/',views.task5,name="books.lab8.task5"),
    path('lab8/task7/',views.task7,name="books.lab8.task7"),
    path('lab9_part1/listbooks/',views.listbooks,name="books.l9p1t1"),
    path('lab9_part1/addbook/',views.addbook,name="books.l9p1t2"),
    path('lab9_part1/editbook/<int:Id>',views.editbook,name="books.l9p1t3"),
    path('lab9_part1/deletebook/<int:Id>',views.deleteBook,name="books.l9p1t4"),
    path('lab9_part2/listbooks/',views.listbooks_django,name="books.l9p2t1"),
    path('lab9_part2/addbook/',views.addbook_django,name="books.l9p2t2"),
    path('lab9_part2/editbook/<int:Id>',views.editbook_django,name="books.l9p2t3"),
    path('lab9_part2/deletebook/<int:Id>',views.deleteBook_django,name="books.l9p2t4"),
    path('lab10/liststudent1t1/',views.liststudent1t1,name="liststudent1t1"),
    path('lab10/addstudent1t1/',views.addstudent1t1,name="addstudent1t1"),
    path('lab10/updatestudent1t1/<int:Id>',views.updatestudent1t1,name="updatestudent1t1"),
    path('lab10/deletestudent1t1/<int:Id>',views.deletestudent1t1,name="deletestudent1t1"),
    path('lab10/liststudentmtm/',views.liststudentmtm,name="liststudentmtm"),
    path('lab10/addstudentmtm/',views.addstudentmtm,name="addstudentmtm"),
    path('lab10/updatestudentmtm/<int:Id>',views.updatestudentmtm,name="updatestudentmtm"),
    path('lab10/deletestudentmtm/<int:Id>',views.deletestudentmtm,name="deletestudentmtm"),
    path('images/', views.listimages, name='listimages'),
    path('images/add/', views.addimage, name='addimage'),
    path('images/edit/<int:Id>/', views.editimage, name='editimage'),
    path('images/delete/<int:Id>/', views.deleteimage, name='deleteimage'),
    path('lab12/task1/', views.changeColorJS, name="books.lab12.task1"),
    path('lab12/task2/', views.addItemJS, name="books.lab12.task2"),
    path('lab12/task3/', views.hideItemJS, name="books.lab12.task3"),
    path('lab12/task4/', views.hoverItemJS, name="books.lab12.task4"),
    path('lab12/task5/', views.createTableJS, name="books.lab12.task5"),
    
]